### ISSUE TITLE
can't start the jar

### ISSUE THREAD

**Issue by Martinligabue** [stefanGT44/AudioVisualizer-RealTime-Spectrogram#1]
when executed it fails immediately throwing
`java.lang.NoClassDefFoundError: javafx/application/Application`

**Comment by Ygarr** [comment]
Cannot run but another Stacktrace
```
 java --module-path C:\SFT\openjfx-18.0.2_windows-x64_bin-sdk\javafx-sdk-18.0.2\lib --add-modules javafx.controls,javafx.fxml -jar .\AudioVisualizerSpectrogramMic.jar
Exception in Application start method
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at javafx.graphics@18.0.2/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:465)
        at javafx.graphics@18.0.2/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:364)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1081)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at javafx.graphics@18.0.2/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
        at javafx.graphics@18.0.2/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoClassDefFoundError: javafx/embed/swing/SwingFXUtils
        at app.View.initWindow(View.java:195)
        at app.View.<init>(View.java:62)
        at app.View.get(View.java:56)
        at app.Main.start(Main.java:23)
        at javafx.graphics@18.0.2/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
        at javafx.graphics@18.0.2/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
        at javafx.graphics@18.0.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at javafx.graphics@18.0.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
        at javafx.graphics@18.0.2/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics@18.0.2/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics@18.0.2/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: javafx.embed.swing.SwingFXUtils
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 13 more
Exception running application app.Main
```

**Comment by stefanGT44** [comment]
Do you have javaFX setup?
If you're running the jar from the downloads folder, there shouldn't be any issues.

**Comment by Ygarr** [comment]
Need something else?
```
ls


    Directory: C:\SFT\openjfx-18.0.2_windows-x64_bin-sdk\javafx-sdk-18.0.2\lib


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         7/19/2022   8:59 PM          37127 javafx-swt.jar
-a----         7/19/2022   8:59 PM         745882 javafx.base.jar
-a----         7/19/2022   8:59 PM        2544033 javafx.controls.jar
-a----         7/19/2022   8:59 PM         129493 javafx.fxml.jar
-a----         7/19/2022   8:59 PM        4254797 javafx.graphics.jar
-a----         7/19/2022   8:59 PM         276001 javafx.media.jar
-a----         7/19/2022   8:59 PM             77 javafx.properties
-a----         7/19/2022   8:59 PM          88807 javafx.swing.jar
-a----         7/19/2022   8:59 PM         726942 javafx.web.jar
```
